In [4]:
import numpy as np

### Basics of Matrix

Cross Product

In [14]:
x = np.array([[1,2,3],[0,9,8]])
y = np.array([[1,2,3],[2,3,4]])

cp = np.cross(x,y)
print(cp)

[[  0   0   0]
 [ 12  16 -18]]


Dot Product

In [16]:
x = np.array([1,2,3])
y = np.array([1,2,3])

dp = np.dot(x,y)
print(dp)

14


Inverse of Matrix

In [39]:
z = np.array([[1,1],[1,2]])
z_inv = np.linalg.inv(z)
print(z_inv)

#inverse test
print("we will get a unit matrix  ", np.dot(z, z_inv))

[[ 2. -1.]
 [-1.  1.]]
we will get a unit matrix   [[1. 0.]
 [0. 1.]]


Determinant of Matrix

In [42]:
det_z = np.linalg.det(z)
print(det_z)

1.0


Eigenvalues and Eigenvectors

In [59]:
big_x = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.linalg.eigvals(big_x)
eigenvalues, eigenvectors = np.linalg.eig(big_x)
print("Eigenvalues:", eigenvalues)
print("Eigenvalues:", eigenvectors)

Eigenvalues: [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Eigenvalues: [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### Co-variance Matrix

In [56]:
import numpy as np

# Create a dataset with two variables (2 columns) and multiple observations (rows)
data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])

# Compute the covariance matrix
cov_matrix = np.cov(data, rowvar=True)

print(cov_matrix)

[[1.66666667 1.66666667]
 [1.66666667 1.66666667]]


### Singular Value decomposition 

In [150]:
big_x = np.array([[1,2,99], [5,7,3], [2,4,28]])
print(np.linalg.det(big_x)) #check if det is not zero

In [153]:
U,sig,Vt = np.linalg.svd(big_x) #singular value decomp

matl = []                           # converting 1D sigma to 3D diagonal matrix 
for j in range(3):
    x_press = []
    for i in range(3):
        if i==j:
            x_press.append(sig[i])
        else:
            x_press.append(0)
    matl.append(x_press)

In [ ]:
#validation for is svd multiplies to original matrix 

new_x = np.dot(U, np.dot(matl,Vt))
print(new_x)

In [156]:
#inverse of big X using standard method 
big_x_inv = np.linalg.inv(big_x)
print(big_x_inv)

[[ 0.36078431  0.66666667 -1.34705882]
 [-0.2627451  -0.33333333  0.96470588]
 [ 0.01176471  0.         -0.00588235]]


In [157]:
#inverse of big_x using svd 
U,sig,Vt
U_inv = np.linalg.inv(U) #inverse of U
sig_inv = np.linalg.inv(matl) #inverse of sig
Vt_inv = np.linalg.inv(Vt) #inverse of Vt 

big_x_invsvd = np.dot(Vt_inv, np.dot(sig_inv, U_inv))
print(big_x_invsvd)

[[ 3.60784314e-01  6.66666667e-01 -1.34705882e+00]
 [-2.62745098e-01 -3.33333333e-01  9.64705882e-01]
 [ 1.17647059e-02  1.03829124e-17 -5.88235294e-03]]


In [164]:
#validation of inverse using SVD 
np.dot(big_x,big_x_invsvd)

array([[ 1.00000000e+00,  1.24995293e-15, -5.35075456e-15],
       [-3.98986399e-17,  1.00000000e+00,  2.44856219e-15],
       [ 8.11850587e-16,  7.34810757e-16,  1.00000000e+00]])

### Solve a System of Linear Equation

big_x is matrix of coefficient and solution matrix is sol_mat

In [185]:
sol_mat = np.array([[-1],[5],[6]])
print("rank of coeffecient matrix", np.linalg.matrix_rank(big_x)) 

rank of coeffecient matrix 3


In [187]:
test_lin = np.array([[1,2,99,-1], [5,7,3,5], [2,4,28,6]])
print("rank of augmented matrix", np.linalg.matrix_rank(test_lin)) #rank of augmented matrix 
#if rank of coeffcient matrix = rank of augmented matrix = number of unknowns then system has unique solution 
#if rank of coeffcient matrix = rank of augmented matrix < number of unknowns then infinite solutions 
# if rank of coeffcient matrix < rank of augmented matrix  then No solution 

rank of augmented matrix 3


In [189]:
np.dot(big_x_inv,sol_mat) #Unique solution matrix

array([[-5.10980392],
       [ 4.38431373],
       [-0.04705882]])

### Principal Component Analysis using SVD

In [8]:
import pandas as pd 
from matplotlib import pyplot as plt
from sklearn.preprocessing import StandardScaler

path = 'C:\\Users\\Dell\\Desktop\\Others\\PCA\\data.csv'
df = pd.read_csv(path)

#check if there are nulls 
cnt_list = []
for j in df.columns:
    cnt = 0
    for i in df.isna()[j]:
        if i == True:
            cnt = cnt+1
    cnt_list.append(cnt)

print(cnt_list)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 569]


In [9]:
df = df.drop(['Unnamed: 32', 'diagnosis'], axis=1)
k = StandardScaler().fit_transform(df)
U,sig,Vt = np.linalg.svd(k)

# The principal components are the rows of Vt (or columns of V.T)
principal_components = Vt.T

z = 2
X_pca = np.dot(k, principal_components[:, :z])

In [10]:
X_pca

array([[ 9.18319983,  1.97127137],
       [ 2.38329766, -3.75345877],
       [ 5.74247239, -1.08035048],
       ...,
       [ 1.2518901 , -1.89397674],
       [10.36503528,  1.69639755],
       [-5.47826365, -0.67278804]])